<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DropDownSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2017-12-09T11:58:13</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f449dae4-422a-476e-85b5-8b1c2545fcbf</testSuiteGuid>
   <testCaseLink>
      <guid>1107f81b-ae85-44f6-b1ac-4269e6e37565</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DropDown/DropdownFunctionScriptMode</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e58467ab-ffbd-443e-a89a-e4965f29f363</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DropDown/DropDownManualMode</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>215032af-38b3-46d8-b4fa-51cd856865dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3417b7c-1558-44f4-8f41-c6c58bae2e6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e10232bc-299b-4822-ae7e-6ae718cca46b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b8679e0-f223-4812-92fb-e071a90d2f9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9580ea74-4b80-420e-ac5d-8b07e0f473a6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
